apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: nextjs
          image: ghcr.io/zainabkousar/nextjs-docker-app:latest
          ports:
            - containerPort: 3000


